[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# NOUVEL AJOUT : Plugin pour installer les dépendances des fonctions
[[plugins]]
  package = "@netlify/plugin-functions-install-core"